### ISSUE TITLE
incorrectly labeled assets

### ISSUE THREAD

**Issue by gramsimamsi** [hsro-inf-prg3/06-annotations-reflection#1]
If i'm getting this correctly, there's something missing in the pictures of Readme.md.  
All module paths "de.fhro.inf.prg3.*" are missing the ".a06.". , which were present in the previous assignments.

As this is quite a difficult issue to comprehend, please consult the visualisation below;  

![image](https://user-images.githubusercontent.com/32511256/35419125-950cea24-0236-11e8-894f-d66e1b9a24f5.png)

:stuck_out_tongue_closed_eyes:

**Comment by baez90** [comment]
You are so right!

I'm going to fix that immediately!
